# Generated by Django 3.2.5 on 2022-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dateofbirth', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=6, null=True)),
                ('placeofbirthid', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('addressid', models.FloatField(blank=True, null=True)),
                ('telephone', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('politicalpartyid', models.IntegerField()),
                ('oldsymbolid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('photocheck', models.FloatField(blank=True, null=True)),
                ('face', models.FloatField(blank=True, null=True)),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('version', models.FloatField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('eligibility', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('documentid', models.FloatField(blank=True, null=True)),
                ('documentnumber', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('educationid', models.IntegerField(blank=True, null=True)),
                ('placeissued', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dateissued', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('isactive', models.BooleanField()),
                ('comment', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dateofcancellation', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dateofcancellationec', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('ballotorder', models.IntegerField(blank=True, null=True)),
                ('dateofregistration', models.DateTimeField(blank=True, null=True)),
                ('dateofregistrationec', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('edituser', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editmachine', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('edituserlog', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editmachinelog', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editdate', models.DateTimeField(blank=True, null=True)),
                ('editdateec', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('disability', models.BooleanField()),
                ('june21', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='June21', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Candidate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('electionid', models.AutoField(primary_key=True, serialize=False)),
                ('electiontype', models.IntegerField()),
                ('electionname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dateofelection', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'election',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoprconstituency',
            fields=[
                ('constituencyid', models.IntegerField(primary_key=True, serialize=False)),
                ('constituencyname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('contype', models.IntegerField()),
                ('isactive', models.BooleanField()),
                ('election_status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Election_Status', max_length=50)),
            ],
            options={
                'db_table': 'HoPRconstituency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kebele',
            fields=[
                ('kebeleid', models.IntegerField(primary_key=True, serialize=False)),
                ('kebelename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('kebelecode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('towncode', models.IntegerField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'kebele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NebeuserUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, unique=True)),
                ('full_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('is_trance', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_checker', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_supperuser', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'nebeuser_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteHopresult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newVote_hopresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteHoprgeneral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('not_aproved', models.BooleanField()),
                ('no_of_pollingstation', models.IntegerField(blank=True, null=True)),
                ('exclude_no_of_pollingstation', models.IntegerField(blank=True, null=True)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
                ('q5', models.IntegerField(blank=True, null=True)),
                ('q6', models.IntegerField(blank=True, null=True)),
                ('q7', models.IntegerField(blank=True, null=True)),
                ('q8', models.IntegerField(blank=True, null=True)),
                ('q9', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newVote_hoprgeneral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteHoprmax',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'newVote_hoprmax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteHoprmemo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'newVote_hoprmemo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteRcgeneral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approve', models.BooleanField()),
                ('not_aproved', models.BooleanField()),
                ('no_of_seat', models.IntegerField()),
                ('no_of_pollingstation', models.IntegerField()),
                ('exclude_no_of_pollingstation', models.IntegerField()),
                ('q1', models.IntegerField(db_column='Q1')),
                ('q2', models.IntegerField(db_column='Q2')),
                ('q3', models.IntegerField(db_column='Q3')),
                ('q4', models.IntegerField(db_column='Q4')),
                ('q5', models.IntegerField(db_column='Q5')),
                ('q6', models.IntegerField(db_column='Q6')),
                ('q7', models.IntegerField(db_column='Q7')),
                ('q8', models.IntegerField(db_column='Q8')),
                ('q9', models.IntegerField(db_column='Q9')),
            ],
            options={
                'db_table': 'newVote_rcgeneral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteRcmax',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'newVote_rcmax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteRcmemo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'newVote_rcmemo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewvoteRcresult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote', models.BigIntegerField()),
            ],
            options={
                'db_table': 'newVote_rcresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Politicatparty',
            fields=[
                ('politicalpartyid', models.IntegerField(primary_key=True, serialize=False)),
                ('politicalpartyname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('politicalpartynameen', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('representative', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('telephone', models.FloatField(blank=True, null=True)),
                ('isindependent', models.BooleanField()),
                ('acronym', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('reason', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('oldsymbolid', models.FloatField(blank=True, null=True)),
                ('isactive', models.BooleanField()),
                ('edituser', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editmachine', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editdate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editdateec', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('regdate', models.FloatField(blank=True, null=True)),
                ('regdateec', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('reguser', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'politicatparty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pollingstation',
            fields=[
                ('voterpollingstationid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('voterpollingstationname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('voterpollingstationcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('pstype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('geocode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('isactive', models.BooleanField()),
                ('iscustom', models.BooleanField(blank=True, null=True)),
                ('editdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'PollingStation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.IntegerField(db_column='regionId', primary_key=True, serialize=False)),
                ('regionname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regionalconstituency',
            fields=[
                ('regionalconstituencyid', models.IntegerField(primary_key=True, serialize=False)),
                ('regionalconstituencyname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('seats', models.IntegerField()),
                ('isactive', models.BooleanField()),
                ('election_status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Election_Status', max_length=50)),
            ],
            options={
                'db_table': 'regionalconstituency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbolid', models.IntegerField(primary_key=True, serialize=False)),
                ('symbolname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('symbolbinary', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('isactive', models.BooleanField()),
                ('edituser', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editmachine', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('editdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'symbol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('woredaid', models.IntegerField(primary_key=True, serialize=False)),
                ('woredaname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('woredacode', models.FloatField(blank=True, null=True)),
                ('issubcity', models.BooleanField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'Woreda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zoneid', models.IntegerField(primary_key=True, serialize=False)),
                ('zonename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('zonecode', models.FloatField(blank=True, null=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
    ]
