# Generated by Django 3.2.5 on 2022-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
