# Generated by Django 3.2.5 on 2022-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_request_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
